[package]
name = "crypto-rs"
version = "0.1.0"
authors = ["Raphael Matile <raphael.matile@gmail.com>"]

[dependencies]
num = {version = "0.2", features = ["serde", "rand"]}
rand = "0.5"
sha2 = "0.7.1"
serde = "1.0"
serde_derive = "1.0"